# Generated by Django 5.1.1 on 2024-10-02 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_department_options_department_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='base.department')),
            ],
            options={
                'ordering': ['-updated', '-created'],
                'unique_together': {('position', 'department')},
            },
        ),
    ]
