# Generated by Django 5.1.1 on 2024-10-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_positionlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionlist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
