# Generated by Django 5.1.1 on 2024-10-03 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_emplist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emplist',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='base.department'),
        ),
        migrations.AlterField(
            model_name='emplist',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='base.positionlist'),
        ),
        migrations.AlterField(
            model_name='positionlist',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='base.department'),
        ),
    ]
